name: Deploy to Firebase Hosting

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    if: ${{ github.actor == github.repository_owner }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: live
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FITAPP_37523 }}
          projectId: fitapp-37523
