name: Semgrep CE scan

on:
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config auto
